import React from 'react';
import { Database } from 'lucide-react';
import Link from 'next/link';

export default function DataPolicyPage() {
    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto bg-white rounded-3xl shadow-xl p-8 sm:p-12 border border-slate-100">
                <div className="flex items-center gap-4 mb-8 pb-8 border-b border-slate-100">
                    <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center">
                        <Database className="w-6 h-6" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Data Policy</h1>
                        <p className="text-slate-500 font-medium">Privacy and Data Management Commitment</p>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-emerald-600">
                    <p>
                        MediaGeny Tech Solutions respects the explicit data sovereignty of our clients. Your guest and property management data is managed with extreme operational integrity and minimal retention.
                    </p>

                    <h3>1. Minimal Context Storage</h3>
                    <p>We log only the requisite application data elements necessary to populate your operations dashboard and provide actionable trend analysis. Personal guest identity markers are treated with the highest data governance protocols.</p>

                    <h3>2. Cloud Residency</h3>
                    <p>Your property intelligence is stored on decentralized secure managed databases. We commit to executing systematic backups with full redundancy layers to ensure persistent disaster recovery support.</p>

                    <h3>3. Consent and Telemetry</h3>
                    <p>No operational metadata or proprietary hospitality insights generated by Geny PMS Pro will ever be brokered to third-party institutions.</p>

                </div>

                <div className="mt-12 pt-8 border-t border-slate-100">
                    <Link href="/login" className="text-sm font-bold text-emerald-600 hover:text-emerald-700 transition-colors">
                        &larr; Return to Login
                    </Link>
                </div>
            </div>
        </div>
    );
}
