-- New migration for Geofencing support
ALTER TABLE restaurant_settings 
ADD COLUMN IF NOT EXISTS geofencing_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS rest_latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS rest_longitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS rest_radius INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS hotel_latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS hotel_longitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS hotel_radius INTEGER DEFAULT 100;
